### ISSUE TITLE
Ch 5 activity seems t is at 0.975

### ISSUE THREAD

**Issue by kvond** [gitrman/itns#3]
Hi Folks,
 When I calculate out the t multiplier for the ch 5 activity it only works to be 2.02 at a confidence level of  0.975 not a 0.95 level. see http://www.sjsu.edu/faculty/gerstman/StatPrimer/t-table.pdf

Am I seeing this correctly?

Thanks!
Kathy

**Comment by gitrman** [comment]
Hi Kathy

Can you be more specific in regard to which part of the Ch5 activity you are referring to -- can  you provide a page or exercise number?

I suspect what you might be asking is -- how come to find the appropriate critical t-value for a 95% confidence interval do you need to use a value from the column in the table you linked to that has a heading of "t.975" rather than "t.95".  The reason is that presumably you are trying to calculate a two-sided 95% confidence interval, whereas the cumulative probabilities listed in the table are one-sided.  Here's a video that might help you understand  (there is a table with one *and* two-sided probabilities about 2 minutes in).

https://www.khanacademy.org/math/statistics-probability/confidence-intervals-one-sample/old-confidence-interval-videos/v/t-statistic-confidence-interval

Hope that helps.

**Comment by kvond** [comment]
Ugh, I see that now - thanks for clearing that up!
K
